# Generated by Django 5.0.1 on 2025-12-24 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Очки за достижение'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='time_played',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Время игры (секунды)'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Очки'),
        ),
    ]
