# Generated by Django 5.0.1 on 2026-01-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_achievement_points_alter_gamesession_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at'], 'verbose_name': 'Дружба', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['rank', '-score'], 'verbose_name': 'Таблица лидеров', 'verbose_name_plural': 'Таблицы лидеров'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
